[package]
name = "bevy_terrain_test"
version = "0.1.0"
edition = "2021"
exclude = ["/assets"]
keywords = ["gamedev"]
categories = ["game-development", "terrain", "bevy", "procedural-generation"]

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
rendering = ["bevy/bevy_render"]
default = ["rendering"]

[dependencies]
bevy = { version = "0.14", default-features = false }
fixedbitset = "0.5"
noise = { version = "0.9", default-features = false }

[dev-dependencies]
criterion = { version = "0.5" }
bevy = { version = "0.14", features = ["jpeg", "dds"] }
bevy_editor_pls = { git = "https://github.com/zhaop/bevy_editor_pls.git", branch = "bevy-0.14" }

[[example]]
name = "basic_setup"
required-features = ["rendering"]

[[bench]]
name = "math"
harness = false