[package]
name = "bevy_terrain_test"
version = "0.1.0"
edition = "2021"

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
rendering = []
default = ["rendering"]

[dependencies]
bevy = { version = "0.14.0", features = ["jpeg"] }
bevy_rapier3d = "0.27.0"
fixedbitset = "0.5.7"
noise = { version = "0.9.0", default-features = false }

[dev-dependencies]
criterion = { version = "0.5" }
bevy_editor_pls = { git = "https://github.com/zhaop/bevy_editor_pls.git", branch = "bevy-0.14" }

[[example]]
name = "basic_setup"
required-features = ["rendering"]

[[bench]]
name = "math"
harness = false