[package]
name = "bevy_world_seed"
version = "0.1.0"
edition = "2021"
exclude = ["/assets"]
keywords = ["gamedev"]
categories = ["game-development", "terrain", "bevy", "procedural-generation"]

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
debug_draw = ["rendering", "bevy/bevy_gizmos"]
rendering = ["bevy/bevy_render", "bevy/bevy_pbr", "bevy/bevy_asset"]
default = ["rendering", "debug_draw"]

[dependencies]
bevy = { version = "0.14", default-features = false }
fixedbitset = "0.5"
noise = { version = "0.9", default-features = false }
splines = "4.3.1"

[dev-dependencies]
criterion = { version = "0.5" }
bevy = { version = "0.14", features = ["jpeg", "dds", "asset_processor"] }
bevy_editor_pls = { git = "https://github.com/zhaop/bevy_editor_pls.git", branch = "bevy-0.14" }
bevy_rapier3d = "0.27.0"

[[example]]
name = "basic_setup"
required-features = ["rendering"]

[[example]]
name = "many_tiles"
required-features = ["rendering"]

[[example]]
name = "terrain_collider"
required-features = ["rendering"]

[[bench]]
name = "math"
harness = false
